### ISSUE TITLE
Submit Button Is Doing Nothing

### ISSUE THREAD

**Issue by stephsharik** [technoplato/knophy#72]
I click on it and it doesn't have an effect.

**Comment by stephsharik** [comment]
![screen shot 2019-01-11 at 3 07 56 pm](https://user-images.githubusercontent.com/26828855/51064155-15c3e600-15b3-11e9-8576-39ad95489cef.png)

**Comment by technoplato** [comment]
Fixed by this! 

https://github.com/technoplato/knophy/commit/03b4a92e2b5b0c383372252cc98e9b3dbba06547

Thanks for pointing it out
