### ISSUE TITLE
Cannot find my content

### ISSUE THREAD

**Issue by stephsharik** [technoplato/knophy#74]
I was able to submit it successfully and transitioned from there to making a question. I made one question and submitted it, but now I can't find the content nor the quiz anywhere.

**Comment by technoplato** [comment]
Something weird is going on.

Everything is working on my local machine, but when I upload the website, this and #73 occur.

This may be the cause: 
![image](https://user-images.githubusercontent.com/6922904/51089590-c9f17800-173d-11e9-969e-707081d25fb0.png)

But I can't find out why that would happen and didn't change anything related that error message (that I know). Aye aye aye. It's the simplest things that are often the most frustrating. 

Will get this figured out.
