### ISSUE TITLE
Dashboard Feature

### ISSUE THREAD

**Issue by stephsharik** [technoplato/knophy#75]
As of right now, I am unable to see:
 - [x] the content I submit
 - [x] the questions I create (and their answers)
 - [x] my 'social' activity (such as making comments. I love how reddit lets me see a page of my post activity, comment activity, and messenger activity. Some version of this would be TOP)
 - [ ] any available quizzes
 - [x] quiz results

I would LOVE a dashboard feature that lets me review the following:

 - [x] Linked content/content submissions
 - [x] Submitted questions (and their answers)
 - [x] Comments made
 - [ ] Quiz lists
 - [x] Quizzes attempted

**Comment by technoplato** [comment]
This is so helpful you have no idea. Thank you for these recommendations.

Really, this is exactly the kind of thing that helps me orient towards what to work on on a given day.

**Comment by technoplato** [comment]
@stephsharik 

For 'available quizzes', we've got to figure out a way to determine if a user is interested in the questions that are available. Any ideas?

Simplest way would just be looking at a list of their 'top earning' people thus far.

**Comment by technoplato** [comment]
@stephsharik I'm going to close this issue for now. I added comments, your post submissions, and questions you've answered on your account page. 

I'll make public profile functionality next so you can see other's profiles (rather than just your own)
